# Generated by Django 2.1 on 2018-09-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.CharField(default='WYS', max_length=30)),
                ('fromsite', models.CharField(max_length=50)),
                ('bookname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='site_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=50)),
                ('bookname', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField()),
                ('lastchapter', models.CharField(max_length=100)),
            ],
        ),
    ]
