# Generated by Django 2.1 on 2018-09-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasStation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='book_info',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='lastchapter',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='sitename',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='updatetime',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='url',
        ),
    ]
