document.writeln("<!-- FOOTER -->");
document.writeln("        <!--===================================================-->");
document.writeln("        <footer id=\'footer\'>");
document.writeln("");
document.writeln("            <!-- Visible when footer positions are fixed -->");
document.writeln("            <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->");
document.writeln("            <div class=\'show-fixed pull-right\'>");
document.writeln("                You have <a href=\'#\' class=\'text-bold text-main\'><span class=\'label label-danger\'>3</span> pending action.</a>");
document.writeln("            </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            <!-- Visible when footer positions are static -->");
document.writeln("            <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->");
document.writeln("            <!-- Remove the class \'show-fixed\' and \'hide-fixed\' to make the content always appears. -->");
document.writeln("            <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->");
document.writeln("");
document.writeln("            <p class=\'pad-lft\'>&#0169; 2018 中国石油化工有限公司</p>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        </footer>");
document.writeln("        <!--===================================================-->");
document.writeln("        <!-- END FOOTER -->");