document.writeln("   <!--NAVBAR-->");
document.writeln("        <!--===================================================-->");
document.writeln("        <header id=\'navbar\'>");
document.writeln("            <div id=\'navbar-container\' class=\'boxed\'>");
document.writeln("");
document.writeln("                <!--Brand logo & name-->");
document.writeln("                <!--================================-->");
document.writeln("                <div class=\'navbar-header\'>");
document.writeln("                    <a href=\'index.html\' class=\'navbar-brand\'>");
document.writeln("                        <img src=\'img/logo.png\' alt=\'Nifty Logo\' class=\'brand-icon\'>");
document.writeln("                        <div class=\'brand-title\'>");
document.writeln("                            <span class=\'brand-text\'>加油站管理系统</span>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <!--================================-->");
document.writeln("                <!--End brand logo & name-->");
document.writeln("");
document.writeln("");
document.writeln("                <!--Navbar Dropdown-->");
document.writeln("                <!--================================-->");
document.writeln("                <div class=\'navbar-content clearfix\'>");
document.writeln("                    <ul class=\'nav navbar-top-links pull-left\'>");
document.writeln("");
document.writeln("                        <!--Navigation toogle button-->");
document.writeln("                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->");
document.writeln("                        <li class=\'tgl-menu-btn\'>");
document.writeln("                            <a class=\'mainnav-toggle\' href=\'#\'>");
document.writeln("                                <i class=\'demo-pli-view-list\'></i>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->");
document.writeln("                        <!--End Navigation toogle button-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                        <!--Notification dropdown-->");
document.writeln("                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->");
document.writeln("                        <li class=\'dropdown\'>");
document.writeln("                            <a href=\'#\' data-toggle=\'dropdown\' class=\'dropdown-toggle\'>");
document.writeln("                                <i class=\'demo-pli-bell\'></i>");
document.writeln("                                <span class=\'badge badge-header badge-danger\'></span>");
document.writeln("                            </a>");
document.writeln("");
document.writeln("                            <!--Notification dropdown menu-->");
document.writeln("                            <div class=\'dropdown-menu dropdown-menu-md\'>");
document.writeln("                                <div class=\'pad-all bord-btm\'>");
document.writeln("                                    <p class=\'text-semibold text-main mar-no\'>You have 9 notifications.</p>");
document.writeln("                                </div>");
document.writeln("                                <div class=\'nano scrollable\'>");
document.writeln("                                    <div class=\'nano-content\'>");
document.writeln("                                        <ul class=\'head-list\'>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li>");
document.writeln("                                                <a href=\'#\'>");
document.writeln("                                                    <div class=\'clearfix\'>");
document.writeln("                                                        <p class=\'pull-left\'>Database Repair</p>");
document.writeln("                                                        <p class=\'pull-right\'>70%</p>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'progress progress-sm\'>");
document.writeln("                                                        <div style=\'width: 70%;\' class=\'progress-bar\'>");
document.writeln("                                                            <span class=\'sr-only\'>70% Complete</span>");
document.writeln("                                                        </div>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li>");
document.writeln("                                                <a href=\'#\'>");
document.writeln("                                                    <div class=\'clearfix\'>");
document.writeln("                                                        <p class=\'pull-left\'>Upgrade Progress</p>");
document.writeln("                                                        <p class=\'pull-right\'>10%</p>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'progress progress-sm\'>");
document.writeln("                                                        <div style=\'width: 10%;\' class=\'progress-bar progress-bar-warning\'>");
document.writeln("                                                            <span class=\'sr-only\'>10% Complete</span>");
document.writeln("                                                        </div>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li>");
document.writeln("                                                <a class=\'media\' href=\'#\'>");
document.writeln("                                            <span class=\'badge badge-success pull-right\'>90%</span>");
document.writeln("                                                    <div class=\'media-left\'>");
document.writeln("                                                        <i class=\'demo-pli-data-settings icon-2x\'></i>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'media-body\'>");
document.writeln("                                                        <div class=\'text-nowrap\'>HDD is full</div>");
document.writeln("                                                        <small class=\'text-muted\'>50 minutes ago</small>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li>");
document.writeln("                                                <a class=\'media\' href=\'#\'>");
document.writeln("                                                    <div class=\'media-left\'>");
document.writeln("                                                        <i class=\'demo-pli-file-edit icon-2x\'></i>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'media-body\'>");
document.writeln("                                                        <div class=\'text-nowrap\'>Write a news article</div>");
document.writeln("                                                        <small class=\'text-muted\'>Last Update 8 hours ago</small>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li>");
document.writeln("                                                <a class=\'media\' href=\'#\'>");
document.writeln("                                            <span class=\'label label-danger pull-right\'>New</span>");
document.writeln("                                                    <div class=\'media-left\'>");
document.writeln("                                                        <i class=\'demo-pli-speech-bubble-7 icon-2x\'></i>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'media-body\'>");
document.writeln("                                                        <div class=\'text-nowrap\'>Comment Sorting</div>");
document.writeln("                                                        <small class=\'text-muted\'>Last Update 8 hours ago</small>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li>");
document.writeln("                                                <a class=\'media\' href=\'#\'>");
document.writeln("                                                    <div class=\'media-left\'>");
document.writeln("                                                        <i class=\'demo-pli-add-user-plus-star icon-2x\'></i>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'media-body\'>");
document.writeln("                                                        <div class=\'text-nowrap\'>New User Registered</div>");
document.writeln("                                                        <small class=\'text-muted\'>4 minutes ago</small>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li class=\'bg-gray\'>");
document.writeln("                                                <a class=\'media\' href=\'#\'>");
document.writeln("                                                    <div class=\'media-left\'>");
document.writeln("                                                        <img class=\'img-circle img-sm\' alt=\'Profile Picture\' src=\'img/profile-photos/9.png\'>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'media-body\'>");
document.writeln("                                                        <div class=\'text-nowrap\'>Lucy sent you a message</div>");
document.writeln("                                                        <small class=\'text-muted\'>30 minutes ago</small>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <!-- Dropdown list-->");
document.writeln("                                            <li class=\'bg-gray\'>");
document.writeln("                                                <a class=\'media\' href=\'#\'>");
document.writeln("                                                    <div class=\'media-left\'>");
document.writeln("                                                        <img class=\'img-circle img-sm\' alt=\'Profile Picture\' src=\'img/profile-photos/3.png\'>");
document.writeln("                                                    </div>");
document.writeln("                                                    <div class=\'media-body\'>");
document.writeln("                                                        <div class=\'text-nowrap\'>Jackson sent you a message</div>");
document.writeln("                                                        <small class=\'text-muted\'>40 minutes ago</small>");
document.writeln("                                                    </div>");
document.writeln("                                                </a>");
document.writeln("                                            </li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("");
document.writeln("                                <!--Dropdown footer-->");
document.writeln("                                <div class=\'pad-all bord-top\'>");
document.writeln("                                    <a href=\'#\' class=\'btn-link text-dark box-block\'>");
document.writeln("                                        <i class=\'fa fa-angle-right fa-lg pull-right\'></i>Show All Notifications");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->");
document.writeln("                        <!--End notifications dropdown-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'nav navbar-top-links pull-right\'>");
document.writeln("");
document.writeln("                        <!--User dropdown-->");
document.writeln("                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->");
document.writeln("                        <li id=\'dropdown-user\' class=\'dropdown\'>");
document.writeln("                            <a href=\'#\' data-toggle=\'dropdown\' class=\'dropdown-toggle text-right\'>");
document.writeln("                                <span class=\'pull-right\'>");
document.writeln("                                    <!--<img class=\'img-circle img-user media-object\' src=\'img/profile-photos/1.png\' alt=\'Profile Picture\'>-->");
document.writeln("                                    <i class=\'demo-pli-male ic-user\'></i>");
document.writeln("                                </span>");
document.writeln("                                <div class=\'username hidden-xs\'>Aaron Chavez</div>");
document.writeln("                            </a>");
document.writeln("");
document.writeln("");
document.writeln("                            <div class=\'dropdown-menu dropdown-menu-md dropdown-menu-right panel-default\'>");
document.writeln("");
document.writeln("                                <!-- Dropdown heading  -->");
document.writeln("                                <div class=\'pad-all bord-btm\'>");
document.writeln("                                    <p class=\'text-main mar-btm\'><span class=\'text-bold\'>750GB</span> of 1,000GB Used</p>");
document.writeln("                                    <div class=\'progress progress-sm\'>");
document.writeln("                                        <div class=\'progress-bar\' style=\'width: 70%;\'>");
document.writeln("                                            <span class=\'sr-only\'>70%</span>");
document.writeln("                                        </div>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("");
document.writeln("");
document.writeln("                                <!-- User dropdown menu -->");
document.writeln("                                <!-- <ul class=\'head-list\'>");
document.writeln("                                    <li>");
document.writeln("                                        <a href=\'#\'>");
document.writeln("                                            <i class=\'demo-pli-computer-secure icon-lg icon-fw\'></i> Lock screen");
document.writeln("                                        </a>");
document.writeln("                                    </li>");
document.writeln("                                </ul> -->");
document.writeln("");
document.writeln("                                <!-- Dropdown footer -->");
document.writeln("                                <div class=\'pad-all text-right\'>");
document.writeln("                                    <a href=\'pages-login.html\' class=\'btn btn-primary\'>");
document.writeln("                                        <i class=\'demo-pli-unlock\'></i> Logout");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->");
document.writeln("                        <!--End user dropdown-->");
document.writeln("");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\' class=\'aside-toggle navbar-aside-icon\'>");
document.writeln("                                <i class=\'pci-ver-dots\'></i>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <!--================================-->");
document.writeln("                <!--End Navbar Dropdown-->");
document.writeln("");
document.writeln("            </div>");
document.writeln("        </header>");
document.writeln("        <!--===================================================-->");
document.writeln("        <!--END NAVBAR-->");