document.writeln("            ");
document.writeln("            <!--MAIN NAVIGATION-->");
document.writeln("            <!--===================================================-->");
document.writeln("            <nav id=\'mainnav-container\'>");
document.writeln("                <div id=\'mainnav\'>");
document.writeln("");
document.writeln("                    <!--Menu-->");
document.writeln("                    <!--================================-->");
document.writeln("                    <div id=\'mainnav-menu-wrap\'>");
document.writeln("                        <div class=\'nano\'>");
document.writeln("                            <div class=\'nano-content\'>");
document.writeln("        ");
document.writeln("                                <ul id=\'mainnav-menu\' class=\'list-group\'>");
document.writeln("						");
document.writeln("						");
document.writeln("						            <!--Menu list item-->");
document.writeln("						            <li>");
document.writeln("						                <a href=\'\\index\\\'>");
document.writeln("						                    <i class=\'demo-psi-home\'></i>");
document.writeln("						                    <span class=\'menu-title\'>");
document.writeln("												<strong>油站管理</strong>");
document.writeln("											</span>");
document.writeln("						                </a>");
document.writeln("						            </li>");
document.writeln("                                     <li class=\'list-divider\'></li>    ");
document.writeln("						            <!--Menu list item-->");
document.writeln("						            <li>");
document.writeln("						                <a href=\'#\'>");
document.writeln("						                    <i class=\'demo-psi-split-vertical-2\'></i>");
document.writeln("						                    <span class=\'menu-title\'>");
document.writeln("												<strong>油枪管理</strong>");
document.writeln("											</span>");
document.writeln("											<i class=\'arrow\'></i>");
document.writeln("						                </a>");
document.writeln("						");
document.writeln("						                <!--Submenu-->");
document.writeln("						                <ul class=\'collapse\'>");
// document.writeln("											<li><a href=\'layouts-aside-right-side.html\'>Aside on the right side</a></li>");
// document.writeln("											<li><a href=\'layouts-aside-left-side.html\'>Aside on the left side</a></li>");
// document.writeln("											<li><a href=\'layouts-aside-dark-theme.html\'>Dark version of aside</a></li>");
document.writeln("											<li class=\'list-divider\'></li>								");
document.writeln("						                </ul>");
document.writeln("						            </li>");
document.writeln("						");
document.writeln("						          ");
document.writeln("						");
document.writeln("						            <li class=\'list-divider\'></li>                             ");
document.writeln("                                </ul>");
document.writeln("");
document.writeln("");
document.writeln("                                <!--Widget-->");
document.writeln("                                <!--================================-->");
document.writeln("                                <div class=\'mainnav-widget\'>");
document.writeln("");
document.writeln("                                    <!-- Show the button on collapsed navigation -->");
document.writeln("                                    <div class=\'show-small\'>");
document.writeln("                                        <a href=\'#\' data-toggle=\'menu-widget\' data-target=\'#demo-wg-server\'>");
document.writeln("                                            <i class=\'demo-pli-monitor-2\'></i>");
document.writeln("                                        </a>");
document.writeln("                                    </div>");
document.writeln("");
document.writeln("                                    <!-- Hide the content on collapsed navigation -->");
document.writeln("                                    <div id=\'demo-wg-server\' class=\'hide-small mainnav-widget-content\'>");
document.writeln("                                        <ul class=\'list-group\'>");
document.writeln("                                            <li class=\'list-header pad-no pad-ver\'>Server Status</li>");
document.writeln("                                            <li class=\'mar-btm\'>");
document.writeln("                                                <span class=\'label label-primary pull-right\'>15%</span>");
document.writeln("                                                <p>CPU 使用率</p>");
document.writeln("                                                <div class=\'progress progress-sm\'>");
document.writeln("                                                    <div class=\'progress-bar progress-bar-primary\' style=\'width: 15%;\'>");
document.writeln("                                                        <span class=\'sr-only\'>15%</span>");
document.writeln("                                                    </div>");
document.writeln("                                                </div>");
document.writeln("                                            </li>");
document.writeln("                                            <li class=\'mar-btm\'>");
document.writeln("                                                <span class=\'label label-purple pull-right\'>75%</span>");
document.writeln("                                                <p>硬盘容量</p>");
document.writeln("                                                <div class=\'progress progress-sm\'>");
document.writeln("                                                    <div class=\'progress-bar progress-bar-purple\' style=\'width: 75%;\'>");
document.writeln("                                                        <span class=\'sr-only\'>75%</span>");
document.writeln("                                                    </div>");
document.writeln("                                                </div>");
document.writeln("                                            </li>");
document.writeln("                                        ");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                                <!--================================-->");
document.writeln("                                <!--End widget-->");
document.writeln("");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <!--================================-->");
document.writeln("                    <!--End menu-->");
document.writeln("");
document.writeln("                </div>");
document.writeln("            </nav>");
document.writeln("            <!--===================================================-->");
document.writeln("            <!--END MAIN NAVIGATION-->");